### PR TITLE
Enhancement of last_hop_responded flag

### PR DESCRIPTION
**Pull request by astrikos**
In some cases we were considering last_hop_responded as True even if all packets of last hop had err in them. According to @PhilipHomburg if we have at least one packet with err it's better if we mark traceroute's last_hop_responded as False.
Tests for new feature included ;)

### CODE REVIEW

**Comment by danielquinn** [comment]
Can you update the Changelog as well?  This sounds like something we should include there.  Otherwise, this looks great.

**Comment by astrikos** [comment]
Sure, I will. I am going to change a bit more after a discussion at the office for correct behaviour.

**Comment by astrikos** [comment]
Okay after some discussion with @PhilipHomburg I changed the logic of last_hop_responded and added another property to show if traceroute finished successfully. If we are okay I will add the these to changes. 
New property is duplicating most of last_hop_responded code but that was the best I could come up this moment, if there is any suggestions to make it better I am open.

**Comment by danielquinn** [comment]
You're right, that does look rather copy/pasty, but I think it should be fine.  You've got the memory-level caching there too which is nice.  If you update the changelog, I'm cool with it.

**Comment by astrikos** [comment]
Okay I made some refactoring cause I need additional property that would add another  duplication of same code. @danielquinn are you happy with this? any suggestions/comments/requests?

**Comment by danielquinn** [comment]
Two things: you've got a `print()` statement in there that should probably go away, and the other is a design note:

I didn't like the copypasta in there, but couldn't think of a better DRY approach than the following.  If you like it, use it.  If you don't, what you've got should be fine too.  I'm really not sure which is better:

```python
    def __init__(self, *args, **kwargs):
        ...
        self.destination_ip_responded = False
        self.last_hop_responded = False
        self.is_success = False
        self.last_hop_errors = []

    def _set_packet_statistics(self, last_hop):

        destination_address = IP(self.destination_address)

        for packet in last_hop.packets:
            if packet.origin and destination_address == IP(packet.origin):
                self.destination_ip_responded = True
            if packet.rtt:
                self.last_hop_responded = True
                if not packet.is_error:
                    self.is_success = True
            if packet.is_error:
                self.last_hop_errors.append(packet.error_message)
            if self.destination_ip_responded:
                if self.last_hop_responded:
                    if self.is_success:
                        if self.last_hop_errors:
                            break
```

**Comment by astrikos** [comment]
I think having multiple function doing one thing is more self-documenting on what is doing. And in general it's easier tested if you want to test for specific properties. Right? I will remove print and add changelog. Should we release or you have more changes in the pipeline?

**Comment by danielquinn** [comment]
Agreed.  As for more changes, I don't have anything other than adding the tests to the manifest, so by all means, let's push all three to Pypi this week.

**Pull request merged**
